version: '3'

services:
  mysql:
    container_name: mysql-container
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  docker_spring:
    container_name: spring-container
    image: docker_spring
    depends_on:
      - mysql
      - kafka
    links:
      - mysql
      - kafka
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/docker_spring
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/docker_spring
      KAFKA_SERVER: kafka:9092
    restart: always